### ISSUE TITLE
Error on activating plugin v.1.3.0 with Shift+T in Blender 2.93.9

### ISSUE THREAD

**Issue by Victor767** [DotBow/Blender-Sticky-UV-Editor-Add-on#4]
Sorry, but it seems nothing is changed with version 1.3.0 in Blender 2.93.9 except for the text of the error itself. Now it looks like this:

```
Python: Traceback (most recent call last):
  File "C:\Users\ViC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sticky_uv_editor\__init__.py", line 363, in invoke
    uv_editor_settings.set(uv_area)
  File "C:\Users\ViC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sticky_uv_editor\uv_editor_settings.py", line 116, in set
    uv_editor.show_faces = self.show_faces
AttributeError: 'SpaceUVEditor' object has no attribute 'use_custom_grid'

location: <unknown location>:-1
```

It still works perfectly fine on Blender 3.2.0 but shows the error shown above in 2.93.9 when activating the script with Shift+T (still it opens UV Editor window) and shows it when you press Shift+T to close UV Editor window but it doesn't close UV Editor window actually, just shows the error message.

**Comment by DotBow** [comment]
Hi!

Can't confirm issue on my side. Try to delete and reinstall add-on from scratch.

**Comment by Victor767** [comment]
I’m so sorry, version 1.3.0 works now on Blender 2.93.9 (also tested on 2.93.8). The thing is earlier I removed version 1.2.0 and installed version 1.3.0 of your plugin from the scratch but for some reason it didn’t work. So I unzipped portable version of Blender 2.93.9 in separate folder, removed Blender settings and addons in AppData/Roaming folder and it worked!!! Now I have to understand what is wrong on my side because the version 1.3.0 really does work on 2.93.9 perfectly well.

Keep up your good work mate!

**Comment by Victor767** [comment]
I’m so sorry, it works now on 2.93.9. The thing is I removed and installed version 1.3.0 of your plugin from the scratch but for some reason it didn’t work. So I unzipped portable version of Blender 2.93.9, removed its settings and addons in AppData/Roaming and it works. Now I have to understand what is wrong on my side. But previous version 1.2.0 didn’t work well with 2.93.9 even after taking steps described above so I hope I don’t bother you and bring a little help anyways 😊

 

Keep up your God blessed work mate!
